apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartfix-api
spec:
  template:
    spec:
      containers:
      - name: smartfix-api
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "512Mi"

