apiVersion: v1
kind: ConfigMap
metadata:
  name: smartfix-config
  namespace: smartfix
data:
  NODE_ENV: "production"
  PORT: "3000"
  JWT_EXPIRES_IN: "7d"
  MONGODB_URI: "mongodb://mongodb-service:27017/smartfix"
  REDIS_URL: "redis://redis-service:6379"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: smartfix
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream smartfix_api {
            server smartfix-api-service:3000;
        }
        
        server {
            listen 80;
            server_name _;
            
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
            
            location / {
                proxy_pass http://smartfix_api;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # Timeouts
                proxy_connect_timeout 60s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;
                
                # Buffer settings
                proxy_buffering on;
                proxy_buffer_size 4k;
                proxy_buffers 8 4k;
            }
        }
    }

