apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: smartfix-dev

commonLabels:
  environment: development

patches:
- path: replicas-patch.yaml

images:
- name: smartfix-api
  newName: ghcr.io/smartfix/smartfix-api
  newTag: dev

