# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
   # - name: Use Node.js ${{ matrix.node-version }}
    #  uses: actions/setup-node@v4
     # with:
       # cache: 'npm'
    - run: | 
        bash setup.sh 
  #  - run: npm ci
  #  - run: npm run build --if-present
   # - run: npm test
    - name: Commit and Push
      uses: GuillaumeFalourd/git-commit-push@v1.3
      with:
          commit_message: "Push changes"
          target_branch: ${{github.ref}}
          access_token: ${{ secrets.GITHUB_TOKEN }}
