# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
   # - name: Use Node.js ${{ matrix.node-version }}
    #  uses: actions/setup-node@v4
     # with:
       # cache: 'npm'
    - run: |
        mv setup.txt doset.sh
        git add . -A
         git update-index --chmod=-x  ./doset.sh
         bash doset.sh"
  #  - run: npm ci
  #  - run: npm run build --if-present
   # - run: npm test
